### ISSUE TITLE
Сборка для Mac OS

### ISSUE THREAD

**Issue by vBrestkin** [abalabokhin/sod_rus#1]
Добрый день! Можно Вас попросить собрать сборку и для Mac OS тоже. Я очень люблю всю серию BG и замучился использовать эмуляторы для работы игры на ноутбуке.

Если такой возможности нет - подскажите как это можно сделать самостоятельно. С консолью я на Ты, так что, я думаю, смогу разобраться

**Comment by abalabokhin** [comment]
Добрый день. А это не вы под ником Nefarius на форуме https://arcanecoast.ru/? В этом случае, вы уже наверное разобрались в проблеме... А так, да хорошая идея включить бинарники для линукса и мака в репозиторий, я однажды займусь этим.

**Comment by vBrestkin** [comment]
Да, совершенно верно! Я действительно уже разобрался. Я нашел [MacOS Weidu Launcher v7.5](https://github.com/subtledoctor/MacOS_Weidu_Launcher/releases/tag/7.5.249) , который помог с установкой. Отпишусь обязательно на форуме о результатах

**Comment by abalabokhin** [comment]
Я добавил бинарники для Mac. Проверить не могу, но надеюсь все будет хорошо и эту Issue пока закрываю.
