### ISSUE TITLE
Не подставляется текст в <PRO_HIMHER>

### ISSUE THREAD

**Issue by ZuevKirill95** [abalabokhin/sod_rus#8]
Не подставляется текст в <PRO_HIMHER>

Пример
```
@69896 = ~Спроси <PRO_HIMHER>.~
@69897 = ~Я не хочу надоедать. Особенно таким, как <PRO_HESHE>.~
@69898 = ~Значит, ты хочешь надоедать только мне? Спроси <PRO_HIMHER>.~
```
В игре выглядит так
![2024-04-20_11-54-11](https://github.com/abalabokhin/sod_rus/assets/30002905/77e19dfd-0739-4d91-b068-af53dad25a5f)

**Comment by abalabokhin** [comment]
Оу, это какойто баг, можешь сейвом поделиться? В целом подстановки у меня работают - но хочу проверить именно этот диалог... Как вариант сделать в этом месте - мужскую/женскую реплику, но вначале хочу посмотреть, как оно у меня будет.

**Comment by abalabokhin** [comment]
Добавлено: это у тебя что-то сломалось (что именно не подскажу в данный момент - у тебя много модов стоит? или может на живую чтото перествлял и что-то пошло не так...). Установил свежий перевод на bg1+sod, телепортировался в нужную область - всё хорошо. Смотри скриншот.

Ну и такой серьезный баг уже бы наверное заметили, если бы он воспроизводился у кого-то еще...
![Screenshot_20240420_141908](https://github.com/abalabokhin/sod_rus/assets/754271/96d925ff-624d-46a3-8b2c-2d573ab36d69)

**Comment by ZuevKirill95** [comment]
Только хотел скинуть сейв, но ты меня опередил)
Модов не ставил. Русификатор ставил по инструкции из стим сообщества - https://steamcommunity.com/sharedfiles/filedetails/?id=1696148262

Может я неправильно обновляю руссификатор, когда появляются новые изменения. 
Я вызываю setup-sodrus и жму Uninstall
Потом в папке sodrus руками меняю файлик sod-russian.tra на свежий файлик
Снова вызываю setup-sodrus и жму Iinstall, а потом Reinstall

**Comment by abalabokhin** [comment]
Правильно ты переставляешь - тогда не знаю, в чем дело (вообще периодически встречаются всякие странные глюки, когда много переставляешь), но как такое отслеживать и фиксить - я хз. В целом, если ты сейчас забекапишь папку игры и установишь все с нуля в другую папку - то текущие сейвы должны без проболем подхватиться и, надеюсь, этот баг уйдет... Что делать кроме этого - я представляю не очень.

**Comment by ZuevKirill95** [comment]
Ну ок, спасиб. 
Возможно, у меня какой-то скрипт сломался
На всякий случай прикреплю сейв
https://disk.yandex.ru/d/WPy5dy9M2HUvZg

**Comment by abalabokhin** [comment]
У меня все хорошо с твоим сейвом. В общем, на свежей установке все должно нормально работать. Можешь проверить?

**Comment by ZuevKirill95** [comment]
Хорошо, спасибо, что проверил
Да, попробую, переустановлю

**Comment by abalabokhin** [comment]
Ну issue я тогда закрываю - что ей висеть?
